app = "arv-local-first-berlin-2025"
primary_region = 'fra'

[build]
image = "registry.hub.docker.com/rocicorp/zero:0.20.2025052100"

[http_service]
internal_port = 4848
force_https = true
auto_stop_machines = 'off'
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2

[mounts]
source = "sqlite_db"
destination = "/data"

[env]
ZERO_REPLICA_FILE = "/data/sync-replica.db"
# ZERO_UPSTREAM_DB="postgresql://postgres:PASSWORD@db.mxynzmougewcnmzmfhif.supabase.co:5432/postgres?sslmode=disable"
ZERO_PUSH_URL="https://ztunes.rocicorp.dev/api/push"
ZERO_AUTH_SECRET="secretkey"
LOG_LEVEL = "debug"
